name: pessoa_bonito
description: Beautify ArquivoPessoa.net

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.4
  html: ^0.15.0
  http: ^0.13.3
  equatable: ^2.0.3
  logger: ^1.1.0
  flutter_spinkit: ^5.1.0
  shared_preferences: ^2.0.7
  json_serializable: ^6.1.4
  json_annotation: ^4.8.1
  get: ^4.6.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  share_plus: ^7.0.2
  url_launcher: ^6.1.12
  vibration: ^1.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  hive_generator: 2.0.0

  flutter_launcher_icons: "^0.9.2"
  flutter_lints: ^1.0.4
  test: ^1.24.3
  mockito: ^5.4.2

# https://github.com/flutter/flutter/issues/127571
dependency_overrides:
  test_api: 0.5.2
  matcher: 0.12.16

flutter:
  uses-material-design: true
  assets:
    - assets/json_files/texts.json
    - assets/json_files/splash_texts.json
    - assets/images/splash_art.jpg

flutter_icons:
  image_path: "assets/icon/icon.png"
  android: true
  ios: false
