name: Build

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v3

      - name: 💎 - Install Flutter
        uses: subosito/flutter-action@v2.10.0
        with:
          flutter-version: '3.x'
          channel: 'stable'

      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: 🌱 - Get dependencies
        run: flutter pub get

      - name: 💅 - Lint
        run: flutter analyze

      - name: 🐛 - Run tests
        run: flutter test

      - name: 🔨 - Build app
        run: flutter build apk --flavor dev --debug
